global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#zateevas-microserv-2'
