FROM golang:1.11

ENV MONGODB_EXPORTER_VERSION=v0.7.0

WORKDIR /go/src/github.com/percona/

RUN apt-get -y install git && \
    git clone https://github.com/percona/mongodb_exporter.git && \
    cd mongodb_exporter && \
    git checkout $MONGODB_EXPORTER_VERSION && \
    make build

FROM quay.io/prometheus/busybox:latest

ENV MONGODB_URI='mongodb://post_db:27017'

COPY --from=0 /go/src/github.com/percona/mongodb_exporter/bin/mongodb_exporter /bin/mongodb_exporter

EXPOSE 9216

ENTRYPOINT [ "/bin/mongodb_exporter" ]

