version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:latest
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post  
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      back_net:
        aliases:
          - comment        
      front_net:
        aliases:
          - comment  

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      back_net:
        aliases:
          - prometheus
      front_net:
        aliases:
          - prometheus  

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
        aliases:
          - node-exporter
      front_net:
        aliases:
          - node-exporter  
  mongodb-exporter:
    image: zateevas/mongodb_exporter

    networks:
      back_net:
        aliases:
          - mongodb-exporter
      front_net:
        aliases:
          - mongodb-exporter

  cloudprober:
    image: ${USERNAME}/cloudprober:latest
    networks:
      back_net:
        aliases:
          - cloudprober        
      front_net:
        aliases:
          - cloudprober


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
