version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:latest
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post  
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      back_net:
        aliases:
          - comment        
      front_net:
        aliases:
          - comment  



volumes:
  post_db:

networks:
  back_net:
  front_net:
